title: "My Blog"
description: "Welcome to movetoday's blog!"
remote_theme: mmistakes/minimal-mistakes

# IMPORTANT !!!
baseurl: "/blog"
url: "https://movetoday.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Navigation menu(상단메뉴)
navigation:
  - title: "Home"
    url: /blog/
  - title: "About"
    url: /blog/about/
  - title: "Posts"
    url: /blog/posts/
